### ISSUE TITLE
Pacpush misses pkg to sync

### ISSUE THREAD

**Issue by Gohub007** [bulletmark/pacpush#2] opened 2021-06-09 11:38 UTC
recently we noticed pacpush misses some of the *.zst files to sync:

$ pacpush -n 192.168.43.54
david-aspirea31553 -> 192.168.43.54: syncing x86_64 package lists ..
/var/lib/pacman/sync/extra.db
/var/lib/pacman/sync/multilib.db
david-aspirea31553 -> 192.168.43.54: getting list of required package updates from 192.168.43.54 ..
* david-aspirea31553 -> 192.168.43.54: alsa-card-profiles-1:0.3.30-1
* david-aspirea31553 -> 192.168.43.54: aom-3.1.1-1
* david-aspirea31553 -> 192.168.43.54: eos-bash-shared-1.7.1-1
* david-aspirea31553 -> 192.168.43.54: evince-40.2-1
* david-aspirea31553 -> 192.168.43.54: gnome-music-1:40.1.1-1
* david-aspirea31553 -> 192.168.43.54: gst-plugin-pipewire-1:0.3.30-1
* david-aspirea31553 -> 192.168.43.54: libcap-2.50-2
* david-aspirea31553 -> 192.168.43.54: pipewire-1:0.3.30-1
* david-aspirea31553 -> 192.168.43.54: pipewire-media-session-1:0.3.30-1
* david-aspirea31553 -> 192.168.43.54: welcome-3.13.1-1
david-aspirea31553 -> 192.168.43.54: syncing updated packages ..
var/cache/pacman/pkg/alsa-card-profiles-1:0.3.30-1-x86_64.pkg.tar.zst
var/cache/pacman/pkg/aom-3.1.1-1-x86_64.pkg.tar.zst.sig
var/cache/pacman/pkg/eos-bash-shared-1.7.1-1-any.pkg.tar.zst.sig
var/cache/pacman/pkg/evince-40.2-1-x86_64.pkg.tar.zst
var/cache/pacman/pkg/gnome-music-1:40.1.1-1-x86_64.pkg.tar.zst.sig
var/cache/pacman/pkg/gst-plugin-pipewire-1:0.3.30-1-x86_64.pkg.tar.zst
var/cache/pacman/pkg/libcap-2.50-2-x86_64.pkg.tar.zst
var/cache/pacman/pkg/pipewire-1:0.3.30-1-x86_64.pkg.tar.zst
var/cache/pacman/pkg/pipewire-media-session-1:0.3.30-1-x86_64.pkg.tar.zst.sig
var/cache/pacman/pkg/welcome-3.13.1-1-any.pkg.tar.zst.sig

today latest update on box 192.168.43.54 after pacpush onto it:

![Bildschirmfoto von 2021-06-09 13-43-18](https://user-images.githubusercontent.com/68228464/121348598-d424fa00-c928-11eb-923c-2c0b841d01e5.png)

**Comment by bulletmark** [comment] 2021-06-09 23:22
Yes, thanks for raising this bug. I can see what the issue is and will fix it soon.

**Comment by bulletmark** [comment] 2021-06-10 00:27
Fixed by commit 60099d83c8a24d3a2e967e924acea61d0d405890 and released as [version 2.9](https://github.com/bulletmark/pacpush/releases/tag/2.9).

**Closed as completed by bulletmark** 2021-06-10 00:27 UTC
